title: Muhammad Sidiq Putra
description: DevOps / Infrastructure Engineer — Kubernetes, Cloud, CI/CD
url: "https://sidiqputra.github.io"
name: Muhammad Sidiq Putra
handle: sidiq@devops
tagline: DevOps / Infrastructure Engineer
email: muhammadsidiqputra@gmail.com
address: Depok, West Java, Indonesia

# Build settings
markdown: kramdown
plugins:
  - jekyll-seo-tag
